/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Core brand
        primary: '#064e3b',
        'on-primary': '#ffffff',
        'primary-container': '#d1fae5',
        'on-primary-container': '#064e3b',
        'primary-fixed': '#9ef4d3',
        'primary-fixed-dim': '#82d7b8',
        'on-primary-fixed': '#002117',
        'on-primary-fixed-variant': '#00513e',

        secondary: '#4b5563',
        'on-secondary': '#ffffff',
        'secondary-container': '#ecfdf5',
        'on-secondary-container': '#065f46',
        'secondary-fixed': '#d3e8db',
        'secondary-fixed-dim': '#b7ccbf',
        'on-secondary-fixed': '#111d19',
        'on-secondary-fixed-variant': '#344b42',

        tertiary: '#b45309',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#fef3c7',
        'on-tertiary-container': '#78350f',
        'tertiary-fixed': '#fde8cf',
        'tertiary-fixed-dim': '#ffb95f',
        'on-tertiary-fixed': '#2a1700',
        'on-tertiary-fixed-variant': '#653e00',

        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',

        background: '#f8faf9',
        'on-background': '#151c27',

        surface: '#f8faf9',
        'on-surface': '#151c27',
        'on-surface-variant': '#404944',
        'surface-variant': '#dee5e0',
        'surface-dim': '#d7dbd7',
        'surface-bright': '#f8faf9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f4f0',
        'surface-container': '#eaeee9',
        'surface-container-high': '#e2e8e4',
        'surface-container-highest': '#dee3de',

        'inverse-surface': '#2a313d',
        'inverse-on-surface': '#ebf1ff',
        'inverse-primary': '#82d7b8',

        outline: '#717972',
        'outline-variant': '#c1c9c2',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '0.25rem',
        sm: '0.5rem',
        md: '1rem',
        lg: '1.5rem',
        xl: '2rem',
        gutter: '1.5rem',
        'container-max': '1440px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        'body-sm': ['Inter'],
        'body-md': ['Inter'],
        'body-lg': ['Inter'],
        'mono-label': ['Inter'],
        'headline-sm': ['Inter'],
        'headline-md': ['Inter'],
        'headline-lg': ['Inter'],
        'display-lg': ['Inter'],
        'label-sm': ['Inter'],
        'label-md': ['Inter'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'mono-label': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
